name: Deployment

on:
  push:
    branches:
      - main

env:
  # 设置时区
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    if: github.repository == 'gtn1024/Blog'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Restore file modification time
        run: |
          git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
      - name: Install pandoc
        run: |
          cd /tmp
          wget -c https://github.com/jgm/pandoc/releases/download/2.19/pandoc-2.19-1-amd64.deb
          sudo dpkg -i pandoc-2.19-1-amd64.deb
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Tencent COS Action
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f / && upload -r ./public/ /
          secret_id: ${{ secrets.SID }}
          secret_key: ${{ secrets.SKEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
